# @package habitat.task

defaults:
  - /habitat/task: task_config_base
  - /habitat/task/actions:
    - rearrange_stop
    - base_velocity
    - arm_action
  - /habitat/task/measurements:
    - ovmm_object_to_place_goal_distance
    - articulated_agent_force
    - force_terminate
    - articulated_agent_colls
    - does_want_terminate
    - num_steps
    - obj_anywhere_on_goal
    - end_effector_to_rest_distance
    - did_pick_object
    - pick_success
    - picked_object_linear_vel
    - picked_object_angular_vel
    - object_at_rest
    - ovmm_placement_stability
    - ovmm_place_success
    - ovmm_dist_to_pick_goal
    - ovmm_rot_dist_to_pick_goal
    - pick_goal_iou_coverage
    - ovmm_nav_to_pick_succ
    - ovmm_nav_orient_to_pick_succ
    - ovmm_dist_to_place_goal
    - ovmm_rot_dist_to_place_goal
    - place_goal_iou_coverage
    - ovmm_nav_to_place_succ
    - ovmm_nav_orient_to_place_succ
    - ovmm_find_object_phase_success
    - ovmm_pick_object_phase_success
    - ovmm_find_recep_phase_success
    - ovmm_place_object_phase_success
    - navmesh_collision
  - /habitat/task/lab_sensors:
    - joint_sensor
    - joint_velocity_sensor
    - object_category_sensor
    - start_receptacle_sensor
    - goal_receptacle_sensor
    - object_segmentation_sensor
    - object_embedding_sensor
    - start_recep_segmentation_sensor
    - goal_recep_segmentation_sensor
    - robot_start_gps_sensor
    - robot_start_compass_sensor
    - camera_pose_sensor
    - end_effector_sensor
    - relative_resting_pos_sensor
    - is_holding_sensor
    - ovmm_nav_goal_segmentation_sensor
    - receptacle_segmentation_sensor
    - all_object_segmentation_sensor
  - _self_

type: OVMMNavToObjTask-v0
reward_measure: ovmm_place_success
success_measure: ovmm_place_success
success_reward: 10.0
slack_reward: -0.005
end_on_success: True
constraint_violation_ends_episode: False
constraint_violation_drops_object: True
object_in_hand_sample_prob: 0.0
base_angle_noise: 0.2618 # 15 degrees
receptacle_categories_file: data/objects/hssd-receptacles.csv
object_categories_file: data/objects/object_categories.csv
actions:
  arm_action:
    type: "ArmAction"
    arm_controller: "ArmRelPosKinematicReducedActionStretch"
    grip_controller: "GazeGraspAction"
    arm_joint_mask: [1,0,0,0,1,1,1,1,1,1]
    arm_joint_dimensionality: 7
    grasp_thresh_dist: 0.8 # for oracle snap
    disable_grip: False
    max_delta_pos: 6.28 # The range of joints are:  [ 0., 0.,  0.,  0.,  0., -1.75, -1.57, -3.14, -3.9, -1.53] -> [0.13, 0.13, 0.13, 0.13, 1.1 , 4., 0.56, 3.14, 1.5 , 0.79], so maximum delta is 6.28
    ee_ctrl_lim: 0.015
    gaze_distance_range: [0.1, 3.0]
    center_cone_angle_threshold: 90.0
    center_cone_vector: [0.0, 1.0, 0.0]
    oracle_snap: True
  base_velocity:
    type: "BaseWaypointTeleportAction"
    navmesh_offset: [[0.0, 0.0]]
    max_displacement_along_axis: 1.0
    max_turn_degrees: 180.0
    allow_lateral_movement: True
    allow_simultaneous_turn: True
measurements:
  force_terminate:
    max_accum_force: -1.0
    max_instant_force: -1.0
  pick_success:
    object_goal: True
    ee_resting_success_threshold: 100
  ovmm_place_success:
    ee_resting_success_threshold: 100
    check_stability: True
  dist_to_pick_goal:
    use_shortest_path_cache: False # when caching, the same set of goals are used throughout
  dist_to_place_goal:
    use_shortest_path_cache: False # when caching, the same set of goals are used throughout
  nav_orient_to_pick_succ:
    must_call_stop: False
    success_angle_dist: 3.14
    min_object_coverage_iou: 1e-3
  nav_orient_to_place_succ:
    must_call_stop: False
    success_angle_dist: 3.14
    min_object_coverage_iou: 1e-3
  nav_to_pick_succ:
    success_distance: 0.1
  nav_to_place_succ:
    success_distance: 0.1
  object_at_rest:
    angular_vel_thresh: 5e-2
    linear_vel_thresh: 5e-3

lab_sensors:
  joint_sensor:
    dimensionality: 10
  joint_velocity_sensor:
    dimensionality: 10