
# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: depthp_head_rgb_third_agent
  - /habitat/task/ovmm: place
  - /habitat/dataset/ovmm: hssd
  - _self_

habitat:
  gym:
    obs_keys:
      - head_depth
      - goal_receptacle
      - object_embedding
      - goal_recep_segmentation
      - joint
      - is_holding
  environment:
    max_episode_steps: 350
  simulator:
    type: OVMMSim-v0
    additional_object_paths:
      - data/objects/train_val/amazon_berkeley/configs/
      - data/objects/train_val/google_scanned/configs/
      - data/objects/train_val/ai2thorhab/configs/objects/
      - data/objects/train_val/hssd/configs/objects/
    needs_markers: False
    debug_render_goal: False
    debug_render: False
    concur_render: True
    auto_sleep: True
    requires_textures: False
    kinematic_mode: True
    agents:
      main_agent:
        radius: 0.3
        height: 1.41
        articulated_agent_urdf: data/robots/hab_stretch/urdf/hab_stretch.urdf
        articulated_agent_type: "StretchRobot"
        ik_arm_urdf: null
        sim_sensors:
           head_depth_sensor:
             height: 640
             width: 480
             hfov: 42
             position: [0,1.31,0]
           head_panoptic_sensor:
             height: 640
             width: 480
             hfov: 42
             position: [0,1.31,0]
    habitat_sim_v0:
      allow_sliding: False
      enable_physics: True
