# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbdp_head_rgb_third_agent
  - /habitat/task/ovmm: ovmm
  - /habitat/dataset/ovmm: hssd
  - _self_

habitat:
  seed: 7
  gym:
    obs_keys:
      - head_depth
      - head_rgb
      - third_rgb
      - start_receptacle
      - goal_receptacle
      - robot_start_gps
      - robot_start_compass
      - joint
      - object_segmentation
      - start_recep_segmentation
      - goal_recep_segmentation
      - object_category
      - camera_pose
      - object_embedding
      - is_holding
      - relative_resting_position
      - ovmm_nav_goal_segmentation
      - receptacle_segmentation
      - all_object_segmentation
  environment:
    max_episode_steps: 1250
  simulator:
    turn_angle: 30
    forward_step_size: 0.25
    type: OVMMSim-v0
    additional_object_paths:
      - data/objects/train_val/amazon_berkeley/configs/
      - data/objects/train_val/google_scanned/configs/
      - data/objects/train_val/ai2thorhab/configs/objects/
      - data/objects/train_val/hssd/configs/objects/
    debug_render_goal: False
    concur_render: True
    auto_sleep: True
    kinematic_mode: True
    agents:
      main_agent:
        radius: 0.3
        height: 1.41
        articulated_agent_urdf: data/robots/hab_stretch/urdf/hab_stretch.urdf
        articulated_agent_type: "StretchRobot"
        ik_arm_urdf: null
        sim_sensors:
           head_rgb_sensor:
             height: 640
             width: 480
             hfov: 42
           head_depth_sensor:
             height: 640
             width: 480
             hfov: 42
           head_panoptic_sensor:
             height: 640
             width: 480
             hfov: 42
    habitat_sim_v0:
      allow_sliding: False
      enable_physics: True
    needs_markers: false
  dataset:
    split: val